---
- name: Configure SNMPv3 Monitoring for Synology NAS with Zabbix
  hosts: localhost
  become: yes
  tasks:
    - name: Update repositories and install libsnmp-dev
      apt:
        update_cache: yes
        name: libsnmp-dev
        state: present

    - name: Stop snmpd daemon
      service:
        name: snmpd
        state: stopped

    - name: Create SNMPv3 user authPrivUser on Zabbix server
      command: "net-snmp-config --create-snmpv3-user -ro -a SHA -A 'myauthphrase' -x AES -X 'myprivphrase' authPrivUser"
      become_user: root

    - name: Start snmpd service
      service:
        name: snmpd
        state: started

- name: Gather SNMP facts from Synology NAS
  hosts: synology_nas
  become: yes
  tasks:
    - name: Gather SNMP facts using SNMP version 3
      snmp_facts:
        host: "{{ inventory_hostname }}"
        version: v3
        level: authPriv
        auth_protocol: SHA
        auth_password: myauthphrase
        privacy_protocol: AES
        privacy_password: myprivphrase
      delegate_to: localhost

- name: Configure Zabbix Host
  hosts: localhost
  tasks:
    - name: Download SNMPv3 Zabbix template
      get_url:
        url: "https://www.zabbix.com/integrations/synology/template_synology_diskstation_snmpv3"
        dest: "/tmp/template_synology_diskstation_snmpv3.xml"

    - name: Import Zabbix template
      zabbix_template:
        server_url: "http://44.211.226.130/zabbix"
        login_user: "Admin"
        login_password: "kjagadish"
        state: present
        template_json: "/tmp/template_synology_diskstation_snmpv3.json"

